% COMPUTE MES ---------------------------------------------------------------------------------
function struc_data = compute_MES(struc_data, current)
if(~isempty(struc_data.signals.MUAPt))    
    struc_data.signals.MES.sig = zeros(floor(current.fs*current.T*1000), ...
                                       current.Nch, ...
                                       length(current.PERSP));
    for iMUAP = 1:current.MMUAP
        MUAPt_sig = compute_MUAPt_sig(...
                        struc_data.signals.MUAP(iMUAP, 1).sig, ...
                        struc_data.signals.MUAPt{iMUAP}.pulse_ind, ...
                        current);
        struc_data.signals.MES.sig = sum(cat(4, ...
                                             struc_data.signals.MES.sig, ...
                                             MUAPt_sig), ...
                                             4);        
    end % for each MUAPt    
    struc_data.signals.MES.sig = ...
        struc_data.signals.MES.sig - mean(struc_data.signals.MES.sig);
else
    error('No MUAPt signals found')
end
