clear
clc
% clf
%values for our low pass filter%
r = 50; %ohms%
c = 1*(10^-9); %farads%
% freq = (0:0.1:10); %100 increments for accuracy
freq = linspace(0, 10, 101);
w = freq*2*(pi)*(10^6);
res = 1./(1+(j*(w*r*c)));
res2 = repelem(0.5,101);

%plot(freq,real(res),'r',freq,res2,'--')

X1=[freq]; %X doesnt change

YMatrix1=[res;res2]; %Stack them like this

createfigure1(X1,YMatrix1)

function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Jan-2020 21:53:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Color',[1 0 0]);
set(plot1(2),'LineStyle','--');

% Create ylabel
ylabel('Gain [v0/vi] (V)');

% Create xlabel
xlabel('Frequency((10^6)Hz)');

% Create title
title('The Gain of a Low Pass Filter');

box(axes1,'on');
grid(axes1,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.501785714285714 0.380357142857143],...
    [0.665666666666667 0.530952380952381],'String',{'Gain of 0.5'});

end