%Ece2412 lab 1, case B part 1

clear
clc
clf
close all
%values for our low pass filter%
r = 50; %ohms%
c = 1*(10^-9); %farads%
% freq = (0:0.1:10); %100 increments for accuracy
freq = linspace(0, 10, 101);
w = freq*2*(pi)*(10^6);
res = 1./(1+(1j*(w*r*c)));
res2 = repelem(0.5,101);

X1 = freq;
YMatrix1 = [res;res2]; 

createfigure(X1, YMatrix1)


%grid minor; % Optional
% grid;

function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Jan-2020 15:35:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix1);
set(semilogx1(1),'Color',[1 0 0]);
set(semilogx1(2),'LineStyle','--');

% Create ylabel
ylabel('Gain [v0/vi] (V)');

% Create xlabel
xlabel('Frequency MHz');

% Create title
title('The Gain of a Low Pass Filter');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log');
% Create textarrow
annotation(figure1,'textarrow',[0.817857142857143 0.721428571428571],...
    [0.706142857142857 0.528571428571429],'String',{'Gain of 0.5'});
end
